rollback;

\set ON_ERROR_STOP On

begin transaction;

-- asset
\i api/asset/add_child_to_asset.sql
\i api/asset/add_parent_to_asset.sql
\i api/asset/add_tag_to_asset.sql
\i api/asset/appliances.sql
\i api/asset/assets.sql
\i api/asset/create_appliance.sql
\i api/asset/create_asset_note.sql
\i api/asset/create_asset_status_event.sql
\i api/asset/create_asset.sql
\i api/asset/create_monitor_read.sql
\i api/asset/create_monitor.sql
\i api/asset/create_tag.sql
\i api/asset/delete_tag.sql
\i api/asset/facilities.sql
\i api/asset/get_asset_children.sql
\i api/asset/get_asset_parents.sql
\i api/asset/modify_appliance.sql
\i api/asset/modify_asset.sql
\i api/asset/modify_monitor_read.sql
\i api/asset/modify_monitor.sql
\i api/asset/modify_tag.sql
\i api/asset/remove_child_from_asset.sql
\i api/asset/remove_parent_from_asset.sql
\i api/asset/remove_tag_from_asset.sql
\i api/asset/set_monitor_next_read_date.sql
\i api/asset/tags.sql
-- billing
-- TODO
-- dashboard
\i api/dashboard/dashboard_data.sql
-- depot
\i api/depot/create_depot.sql
\i api/depot/create_supply.sql
\i api/depot/delete_supply.sql
\i api/depot/modify_depot.sql
\i api/depot/modify_supply.sql
-- files
\i api/files/delete_avatar.sql
\i api/files/delete_file.sql
\i api/files/modify_avatar.sql
\i api/files/upload_asset_files.sql
\i api/files/upload_billing_files.sql
\i api/files/upload_depot_files.sql
\i api/files/upload_plan_files.sql
\i api/files/upload_project_files.sql
\i api/files/upload_task_files.sql
-- firm
\i api/firm/create_firm.sql
\i api/firm/modify_firm.sql
-- options
\i api/options/asset_options.sql
\i api/options/create_task_status.sql
\i api/options/depot_options.sql
\i api/options/person_options.sql
\i api/options/project_options.sql
\i api/options/team_options.sql
-- plan
\i api/plan/add_asset_to_task_template.sql
\i api/plan/create_plan.sql
\i api/plan/create_task_from_template.sql
\i api/plan/create_task_template.sql
\i api/plan/modify_plan.sql
\i api/plan/modify_task_template.sql
\i api/plan/remove_asset_from_task_template.sql
-- project
\i api/project/activate_project.sql
\i api/project/add_task_to_project.sql
\i api/project/create_project.sql
\i api/project/deactivate_project.sql
\i api/project/delete_project.sql
\i api/project/modify_project.sql
\i api/project/projects.sql
\i api/project/remove_task_from_project.sql
-- task
\i api/task/add_asset_to_task.sql
\i api/task/clone_task.sql
\i api/task/create_task_note.sql
\i api/task/create_task.sql
\i api/task/delete_task_note.sql
\i api/task/filter_tasks.sql
\i api/task/finish_task.sql
\i api/task/follow_task.sql
\i api/task/modify_task_note.sql
\i api/task/modify_task.sql
\i api/task/remove_asset_from_task.sql
\i api/task/send_task.sql
\i api/task/set_task_date_limit.sql
\i api/task/set_task_status.sql
\i api/task/tasks.sql
\i api/task/unfollow_task.sql
-- team
\i api/team/activate_person.sql
\i api/team/activate_team.sql
\i api/team/active_persons.sql
\i api/team/add_person_to_team.sql
\i api/team/change_password.sql
\i api/team/create_person.sql
\i api/team/create_team.sql
\i api/team/deactivate_person.sql
\i api/team/deactivate_team.sql
\i api/team/modify_myself.sql
\i api/team/modify_person.sql
\i api/team/modify_team.sql
\i api/team/persons.sql
\i api/team/remove_person_from_team.sql
\i api/team/teams.sql
-- utilities
\i api/utilities/create_energy_bill.sql
\i api/utilities/create_water_bill.sql
\i api/utilities/energy_bills.sql
\i api/utilities/modify_energy_bill_note.sql
\i api/utilities/modify_water_bill.sql
\i api/utilities/water_bills.sql

commit transaction;

\unset ON_ERROR_STOP
