\unset ON_ERROR_STOP
\unset QUIET
\unset all_mutations
\unset alloc_to_be_deleted
\unset another_alloc_id
\unset another_spec_id
\unset api_test_ok
\unset asset_category_air
\unset asset_category_electric
\unset asset_category_facility
\unset asset_category_hydro
\unset db_was_populated
\unset errcode_RF101
\unset errcode_RF104
\unset function_name
\unset insert_energy_bills
\unset invoice_to_be_deleted
\unset my_boolean_test
\unset new_alloc_id
\unset new_appliance_id
\unset new_asset_id
\unset new_box_id
\unset new_comment
\unset new_db_name
\unset new_depot_id
\unset new_ext_alloc_id
\unset new_ext_box_id
\unset new_ext_spec_id
\unset new_firm_id
\unset new_invoice_id
\unset new_monitor_id
\unset new_monitor_read_id
\unset new_person_id
\unset new_plan_id
\unset new_price_id
\unset new_project_id
\unset new_purchase_id
\unset new_spec_id
\unset new_supply_id
\unset new_tag_id
\unset new_task_event_id
\unset new_task_id
\unset new_task_template_id
\unset new_team_id
\unset no_periodicity_task_template_id
\unset not_used_output
\unset original_box_id
\unset project_to_be_deleted
\unset purchase_to_be_deleted
\unset supply_to_be_deleted
\unset supply_to_be_removed_from_task
\unset tag_to_be_deleted
\unset test_result_message
\unset tested_mutation
\unset third_spec_id
\unset total_of_mutations
\unset total_tested_mutations
\unset trigger_name
