drop view if exists api.ceb_data;
create or replace view api.ceb_data as
  select
    b.ceb_meter_id,
    b.year,
    b.month,
    b.note,
    b.modalidade,
    b.icms,
    b.cip,
    b.cofins,
    b.irrf,
    b.csll,
    b.pis,
    b.juros,
    b.desconto,
    b.bc,
    b.vliq,
    b.vbru,
    b.kwh_medido,
    b.kwh_faturado,
    b.kwh,
    b.kwh_p,
    b.kwh_f,
    b.dm,
    b.dm_p,
    b.dm_f,
    b.df,
    b.df_p,
    b.df_f,
    b.ufer,
    b.ufer_p,
    b.ufer_f,
    b.verex,
    b.verex_p,
    b.verex_f,
    b.vdf,
    b.vdf_p,
    b.vdf_f,
    b.vud,
    b.vud_p,
    b.vud_f,
    b.dc,
    b.dc_p,
    b.dc_f,
    m.ceb_meter_sf,
    m.description,
    to_date(b.dtvenci, 'YYYYMMDD') as dt_vencimento,
    to_date(b.dtltan, 'YYYYMMDD') as dt_leitura_anterior,
    to_date(b.dtltat, 'YYYYMMDD') as dt_leitura_atual,
    to_date(b.dtapres, 'YYYYMMDD') as dt_apresentacao,
    b.leitant::integer as leitura_anterior,
    b.leitatu::integer as leitura_atual
  from ceb_bills as b
  inner join ceb_meters as m using (ceb_meter_id)
;
