create table ceb_meters (
  ceb_meter_id integer primary key,
  ceb_meter_sf text not null,
  description text not null
);

create table ceb_meter_assets (
  ceb_meter_id integer not null references ceb_meters (ceb_meter_id),
  asset_id integer not null references assets (asset_id)
);

create table ceb_bills (
  -- CLIENTE
  ceb_meter_id integer references ceb_meters (ceb_meter_id),
  -- T.
  t text,
  -- DES.CODFAT
  des_codfat text,
  -- NOME
  name text,
  -- CPF/CNPJ
  cnpj text,
  -- ENDERECO
  address text,
  -- CIDADE
  city text,
  -- UF
  uf text,
  -- CEP
  cep text,
  -- D
  d text,
  -- MEDIDOR
  meter text,
  -- FATORMU
  mu_factor text,
  -- MES.FT
  month integer,
  -- DT.LT.AN
  last_measure_date date,
  -- LEIT.ANT
  last_measure integer,
  -- DT.LT.AT
  current_measure_date date,
  -- LEIT.ATU
  current_measure integer,
  -- DIA
  day integer,
  -- DT.APRES
  print_date date,
  -- DT.VENCI
  due_date date,
  -- VAL.CON.FAT
  val_con_fat numeric,
  -- VALOR.ICMS
  valor_icms numeric,
  -- ALIQU.ICMS
  aliq_icms numeric,
  -- VALOR.CIP
  valor_cip numeric,
  -- RET.COFINS
  ret_cofins numeric,
  -- RETEN.IRRF
  ret_irrf numeric,
  -- RETEN.CSLL
  ret_csll numeric,
  -- RETEN.PIS
  ret_pis numeric,
  -- VAL.ACR.MOR
  val_acr_mor numeric,
  -- VAL.DIV.ACR
  val_div_acr numeric,
  -- VAL.DIV.DES
  val_div_des numeric,
  -- VAL.BASECAL
  val_basecal numeric,
  -- VAL.TRIBUTO
  val_tributo numeric,
  -- VAL.ENERGIA
  val_energia numeric,
  -- VAL.ENC.SET
  val_enc_set numeric,
  -- VAL.TRANSMI
  val_trasmi numeric,
  -- VAL.DISTRIB
  val_distrib numeric,
  -- VAL.TOT.LIQ
  val_tot_liq numeric,
  -- VAL.TOT.BRU
  val_tot_bru numeric,
  -- CONS.MED
  cons_med integer,
  -- CONS.FAT
  cons_fat integer,
  -- MD.A.KWH
  md_a_kwh integer,
  -- DES.CONJ.ELETR
  des_conj_eletr text,
  -- MES.RE
  mes_re text,
  -- DIC.APUR
  dic_apur numeric,
  -- FIC.APUR
  fic_apur numeric,
  -- DMICAPUR
  dmic_apur numeric,
  -- DIC.META
  dic_meta numeric,
  -- FIC.META
  fic_meta numeric,
  -- DMICMETA
  dic_meta numeric,
  -- FT.POT
  ft_pot numeric,
  -- FTPOTP
  ft_pot_p numeric,
  -- FTPOFP
  ft_pot_fp numeric,
  -- CON.FT.P
  con_ft_p integer,
  -- CON.FTFP
  con_ft_fp integer,
  -- DEMAN.MD
  dem_md integer,
  -- DEMA.M.P
  dem_m_p integer,
  -- DEM.M.FP
  dem_m_fp integer,
  -- DEMAN.FT
  dem_fat integer,
  -- DEM.FT.P
  dem_fat_p integer,
  -- DE.FT.FP
  dem_fat_fp integer,
  -- EX.R.CON
  ex_r_con integer,
  -- EX.R.C.P
  ex_r_con_p integer,
  -- EX.R.CFP
  ex_r_con_fp integer,
  -- EX.R.DEM
  ex_r_dem integer,
  -- EX.R.DMP
  ex_r_dem_p integer,
  -- EX.RDMFP
  ex_r_dem_fp integer,
  -- VAL.EXCONSU
  val_ex_r_cons numeric,
  -- VAL.EXCON.P
  val_ex_r_cons_p numeric,
  -- VAL.EXCONFP
  val_ex_r_cons_fp numeric,
  -- VAL.CONFT.P
  val_cons_fat_p numeric,
  -- VAL.CONFTFP
  val_cons_fat_fp numeric,
  -- VAL.EXC.DEM
  val_ex_dem numeric,
  -- VAL.EXCDEMP
  val_ex_dem_p numeric,
  -- VAL.EXDEMFP
  val_ex_dem_fp numeric,
  -- VAL.DEM.FAT
  val_dem_fat numeric,
  -- VAL.DEMFT.P
  val_dem_fat_p numeric,
  -- VAL.DEMFTFP
  val_dem_fat_fp numeric,
  -- VAL.DEM.ULT
  val_dem_ult numeric,
  -- VAL.DEMULTP
  val_dem_ult_p numeric,
  -- VAL.DEMULFP
  val_dem_ult_fp numeric,
  -- DM.CONTR
  dem_contr integer,
  -- DM.CONTP
  dem_contr_p integer,
  -- DM.CONFP
  dem_contr_fp integer,
  -- NOTAFISCAL
  nf integer,
  -- COKWH
  cokwh numeric,
  -- COKW
  cokw numeric,
  -- COKVA
  cokva numeric,
  -- %PERD
  loss_perc numeric,
  -- VAL.PIS
  val_pis numeric,
  -- VLCOFINS
  val_cofins numeric,
  -- VLICMSUB
  val_icmsub numeric,
  -- VLACRBAN
  val_acr_ban numeric,
  -- LTANTKVA
  ltantkva numeric,
  -- LTATUKVA
  ltatukva numeric,
  -- DEM.HSVD
  dem_hsvd numeric,
  -- TS-N
  ts_n1 integer,
  -- TS-N
  ts_n2 integer,
  -- LIMI
  limi1 integer,
  -- LIMI
  limi2 integer,
  -- LIMS
  lims1 integer,
  -- LIMS
  lims2 integer,
  -- CODIGO DE BARRAS DA FATURA
  barcode text,
  ------------------------------
  -- add generated columns here
  note text,
  primary key (ceb_meter_id, month)
);