create table asset_categories (
  asset_category_id integer primary key,
  asset_category_text text not null,
  description text
);

insert into asset_categories values
  (:'asset_category_facility'::integer, 'Complexo Arquitetônico do Senado Federal', 'Descrição do CASF.'),
  (:'asset_category_electric'::integer, 'Sistema elétrico', 'Descrição do sistema elétrico.'),
  (:'asset_category_air'::integer, 'Sistema de climatização', null),
  (:'asset_category_hydro'::integer, 'Sistema hidráulico', null)
;

create table asset_statuses (
  asset_status_id integer primary key,
  asset_status_text text not null
);

insert into asset_statuses values
  (1, 'OK'),
  (2, 'Interditado'),
  (3, 'Inoperante'),
  (4, 'Danificado')
;

create table task_statuses (
  task_status_id integer primary key generated by default as identity,
  task_status_text text not null,
  is_locked boolean not null
);

insert into task_statuses values
  (default, 'Fila de espera', false), -- 1
  (default, 'Pendente', false),       -- 2
  (default, 'Em execução', false),    -- 3
  (default, 'Suspensa', false),       -- 4
  (default, 'Em análise', true),      -- 5
  (default, 'Cancelada', true),       -- 6
  (default, 'Concluída', true)        -- 7
;

create table task_priorities (
  task_priority_id integer primary key,
  task_priority_text text not null
);

insert into task_priorities values
  (1, 'Baixa'),
  (2, 'Normal'),
  (3, 'Alta'),
  (4, 'Urgente')
;

create table task_categories (
  task_category_id integer primary key,
  task_category_text text not null
);

insert into task_categories values
  (1, 'Ar-condicionado'),
  (2, 'Elétrica'),
  (3, 'Elevador'),
  (4, 'Avaliação Estrutural'),
  (5, 'Exaustor'),
  (6, 'Forro'),
  (7, 'Geral'), -- ????
  (8, 'Hidrossanitário'),
  (9, 'Infiltração'),
  (10, 'Marcenaria'),
  (11, 'Piso'),
  (12, 'Revestimento'),
  (13, 'Serralheria'),
  (14, 'Vedação'),
  (15, 'Vidraçaria')
;

create table person_roles (
 person_role text primary key,
 person_role_text text not null
);

insert into person_roles values
  ('administrator', 'Administrador'),
  ('supervisor', 'Servidor da SINFRA'),
  ('inspector', 'Terceirizado da Fiscalização'),
  ('employee', 'Terceirizado da Manutenção'),
  ('visitor', 'Visitante')
;

create table periodicities (
  periodicity_id integer primary key,
  periodicity_text text not null,
  periodicity_days integer,
  days_range integer
);

insert into periodicities values
  (0, 'Sob demanda', null, null),
  (1, 'Diária', 1, 0),
  (7, 'Semanal', 7, 1),
  (15, 'Quinzenal', 15, 2),
  (30, 'Mensal', 30, 7),
  (60, 'Bimestral', 60, 10),
  (90, 'Trimestral', 90, 15),
  (180, 'Semestral', 180, 20),
  (365, 'Anual', 365, 30),
  (730, 'Bienal', 730, 60)
;

create table price_source_types (
  price_source_type_id integer primary key,
  price_source_type_text text not null
);

insert into price_source_types values
  (1, 'SINAP'),
  (2, 'Contrato'),
  (3, 'Proposta de empresa')
;

create table units (
  unit_id integer primary key,
  unit_text text not null,
  dimensions integer not null
);

insert into units values
  (1, 'L', 1),
  (2, 'm', 1),
  (3, 'm²', 2),
  (4, 'm³', 3),
  (5, 'kg', 1),
  (6, 'hh', 1),
  (7, 'un.', 1),
  (8, 'pç.', 1),
  (9, 'par', 1),
  (10, 'Frasco de 150 mL', 1),
  (11, 'Frasco de 500 mL com aplicador', 1),
  (12, 'Pacote de 900 mL', 1),
  (13, 'Saco de 20 kg', 1),
  (14, 'Saco de 40 kg', 1),
  (15, 'Saco de 50 kg', 1),
  (16, 'Rolo com 40 espiras', 1),
  (17, 'unidade x mês', 1),
  (18, 'metro linear', 1),
  (19, 'm x mês', 1),
  (20, 'm² x mês', 2),
  (21, 'm³ / km', 3),
  (22, 'conj x mês', 1),
  (23, 'Profissional', 1),
  (24, 'Dia de uso efetivo', 1)
;

create table monitor_categories (
  monitor_category_id integer primary key,
  monitor_category_text text not null
);

insert into monitor_categories values
  (1, 'Acumulador'),
  (2, 'Valor instantâneo')
;

create table depot_categories (
  depot_category_id integer primary key,
  depot_category_text text not null
);

insert into depot_categories values
  (1, 'Contrato/ARP'),
  (2, 'Em licitação'),
  (3, 'Reserva Técnica')
;

create table supply_categories (
  supply_category_id integer primary key,
  supply_category_text text not null
);
  
insert into supply_categories values
  (1, 'Material'),
  (2, 'Serviço')
;

create table alloc_statuses (
  alloc_status_id integer primary key,
  alloc_status_text text not null
);

insert into alloc_statuses values
  (1, 'Alocado'),
  (2, 'Proposto'),
  (3, 'Aprovado')
;
